gesdinet_jwt_refresh_token:
    refresh_token_class: App\Domain\Entity\RefreshToken
    user_identity_field: email
    # On refresh request: delete the current refresh token and then generate a new one.
    single_use: true
    ttl: 2592000
    ttl_update: true
    token_parameter_name: refreshToken
    return_expiration: true
    return_expiration_parameter_name: refreshTokenExpiration
