nelmio_api_doc:
    documentation:
        info:
            title: Spamer API
            # description: This is an awesome app!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/(?!/doc$)(?!/doc.json$)
        # host_patterns:
        #     - ^api\.
