security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users:
            id: App\Security\ApiUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/v1/
            stateless: true
            entry_point: jwt
            json_login:
                check_path: api.auth.login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email
                password_path: password
            jwt:
                provider: null
                authenticator: lexik_jwt_authentication.security.jwt_authenticator
            refresh_jwt:
                check_path: api.auth.token.refresh

    access_control:
        - { path: ^/v1/auth, roles: PUBLIC_ACCESS }
        - { path: ^/v1, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: plaintext
