version: '3.5'

services:
  database:
    container_name: spamer_test_db
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 67890
      POSTGRES_DB: spamer
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
