doc.swagger.json:
    path: /doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

doc.swagger:
   path: /doc
   methods: GET
   defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
